version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "netplus"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight-container
    restart: always
    ports:
      - "5540:5540"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
