spring:
  application:
    name: Netplus
  datasource:
    url: jdbc:mysql://localhost:3306/netplus
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true