spring:
  application:
    name: Netplus
  datasource:
    url: jdbc:mysql://localhost:3306/netplus
    username: root
    password: 12121212
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  # redis
  data:
    redis:
      host: localhost
      port: 6379
# jwt
jwt:
  secretKey: "VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXk="
  expiration: 3600000
